### ISSUE TITLE
Lack Gtk.StyleProviderPriority

### ISSUE THREAD

**Issue by trinhanhngoc** [openmedicus/gtk-sharp#12]
`GTK_STYLE_PROVIDER_PRIORITY_*` defined in gtkstyleprovider.h:
https://git.gnome.org/browse/gtk+/tree/gtk/gtkstyleprovider.h

**Comment by mikkeljohnsen** [comment]
In what C funtion are this GTK_STYLE_PROVIDER_PRIORITY_\* used ?

**Comment by trinhanhngoc** [comment]
`gtk_style_context_add_provider` and `gtk_style_context_add_provider_for_screen`
https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#gtk-style-context-add-provider

**Comment by mikkeljohnsen** [comment]
I just pushed this. Will that do ?

https://github.com/openmedicus/gtk-sharp/commit/b898323bba7e8334f59cbe8551c3200fb441adf9

**Comment by trinhanhngoc** [comment]
LGTM, thank you.
