### ISSUE TITLE
Wrong signature on TextView.GetIterAtPosition

### ISSUE THREAD

**Issue by wolfgangmauer** [openmedicus/gtk-sharp#35]
Hi,
the signature for the follow method is wrong
Treeview
public bool GetIterAtPosition (TextIter iter, out int trailing, int x, int y);

should be 
public bool GetIterAtPosition (**out** TextIter iter, out int trailing, int x, int y);

**Comment by mikkeljohnsen** [comment]
Hi,

This repository is deprecated please use GLibSharp/GtkSharp or even better this: GtkSharp/GtkSharp
